### ISSUE TITLE
watcher seems to not be watching sass files for updates

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll-watch#10]
For some reason, the SCSS/Sass isn't being watched or isn't being auto-reloaded. Maybe a cache issue? Maybe an issue here.

/cc @jglovier (https://github.com/jekyll/jekyll/issues/2987) and @ttimsmith (https://github.com/jekyll/jekyll/issues/2950).

**Comment by Merovex** [comment]
Also found that it won't work if the `_sass` dir is in the exclude array in `_config.yml`

**Comment by yordis** [comment]
I am using jekyll-assets and the same problem! I remove the exclude line for see if that is the problem but didn't work.
