### ISSUE TITLE
How can I get jekyll to watch an excluded directory?

### ISSUE THREAD

**Issue by philipmjohnson** [jekyll/jekyll-watch#12]
For the Morea Framework (http://morea-framework.github.io/), I have written a Jekyll plugin to specially process a subdirectory, and so I exclude this directory in my config.yml.   Up until recently, the --watch command did the "right thing", in that I could make changes to my excluded subdirectory and Jekyll would regenerate upon the change (which would re-invoke my plugin).

This stopped working, and I've hunted around until I discovered this plugin (apparently as of Jekyll 2.1) in which the watcher doesn't watch excluded files/directories.  

I get that this makes a lot of sense for a lot of use cases, but unfortunately it is bad for my use case. 

I would like your guidance on the best way to re-enable "watching" on directories that are excluded from other Jekyll processing.  Thanks!

**Comment by parkr** [comment]
> Would it be possible for me to override the listen_ignore_path method in my plugin file so that it doesn't ignore my morea directory? If so, can you give me a hint on how to do that? If that's not the right way, what do you recommend?

You can monkey-patch it if you'd like. It's definitely not recommended, but certainly possible. In your plugin,

```ruby
module Jekyll
  class Watcher
    def custom_excludes(options)
      Array(options['exclude']).map { |e| Jekyll.sanitized_path(options['source'], e) unless e =~ /my_special_dir/ }.compact
    end
  end
end
```

**Comment by parkr** [comment]
The watcher only excludes things you tell it to exclude. Jekyll ignores anything with a `_` prefix, so put the plugin stuff in a `_my_plugin_input` folder and you're good.
