### ISSUE TITLE
Support Listen 3.x

### ISSUE THREAD

**Issue by e2** [jekyll/jekyll-watch#24]
Listen 3.x is a major rewrite, and among other things greatly reduces CPU usage and should be a lot more responsive - especially in the worst case scenarios (should make web designers much happier).

Here are the release notes: https://github.com/guard/listen/releases/tag/v3.0.0

(Neither the API differences nor the lack of TCP in Listen 3.x affect Jekyll::Watch at all).

Generally, Listen 3.x is the *primary* version, and Listen 2.x is discouraged. 

So it's best if you lock to Listen ``~> 3.0``. 

While you can just lock to: `'>= 2.10.1', '< 4.0.0'`, I'm sure users will appreciate if 2.x is no longer possible to use with the latest jekyll-watch version.

Report/forward issues to https://github.com/guard/listen as usual.

**Comment by parkr** [comment]
Fixed in #25
