### ISSUE TITLE
Symlinking the _posts directory

### ISSUE THREAD

**Issue by Joshfindit** [jekyll/jekyll-watch#26]
I've created a folder in Dropbox to contain all the posts, and have:

    ~/Dropbox/Posts/Category1
    ~/Dropbox/Posts/Category2
    ...

I've linked using ```ln -s ~/Dropbox/Posts/Category1 ./_posts``` or ```~/Dropbox/Posts/Category1 ./Category1/_posts``` from the Jekyll directory.

Jekyll serve does parse everything the first time, but then does not regenerate when new posts are added to ```~/Dropbox/Posts/Category1```.

*Tested with current and pre. OSX 10.11 Beta 15A243d*

**Comment by parkr** [comment]
This is a limitation of FSNotify. @willnorris has a one-off patch for this somewhere. Maybe check his personal site's repo? Under `_plugins`.

**Comment by willnorris** [comment]
here's the plugin I use for a symlinked `_drafts` folder: https://github.com/willnorris/willnorris.com/blob/master/src/_plugins/symlink_watcher.rb

**Comment by Joshfindit** [comment]
Excellent, @willnorris, thank you. That worked without modification for site/Category/_posts where _posts is a symlink.

In sleeping on this problem, is it acceptable to:
1. Find where a symlink links to
2. Watch the originating folder instead of the symlink

If this is something that could make it in to master, I'd start working on a PR.

**Comment by willnorris** [comment]
yeah, there's already in issue for this: #20.  I started working on it, but the thing that held me up was trying to find a clean way to respect the paths ignored by jekyll's `exclude` config option.  It's totally doable, I just didn't have the time to push through it and find a clean solution I was happy with, so I've just stuck with my little plugin.

**Comment by Joshfindit** [comment]
Right on.
Seeing that it's only 1 of the 5 open issues, and that you have written a whole post about it was a d'oh moment.

Moved the discussion there.
