### ISSUE TITLE
Forking Jekyll leaves unterminated celluloid actors

### ISSUE THREAD

**Issue by untra** [jekyll/jekyll-watch#28]
Alright, this is a bizarre problem for a ridiculous use case, so I apologize in advance if there is no easy solution to this.

Jekyll uses Jekyll-watch to check for changes to files when rebuilding. Jekyll-watch uses the listen gem, which in turn uses celluloid in some manner. Celluloid is used to provide asynchronous processes to listen in some manner.

**My problem:** I am writing a multi-language Jekyll plugin that needs to call `site.process`  in different forks. Each fork is meant to build the site in a different language. We have a large website being built with Jekyll with enough multi-language content that considerable time is saved making multiple forks in this location in `jekyll site`.

Effectively the plugin code looks like:
```ruby
module Jekyll
class site
...
alias_method :process_orig, :process
    def process
      prepare
      pids = {}
      languages.each do |lang|
        pids[lang] = fork do
          process_language lang #calls process_orig 
        end
      end
      languages.each do |lang|
        waitpid(pids[lang])
      end
    end
```

The site builds correctly the first time it runs. Subsequent builds work correctly as well, but they all throw a loud error from celluloid:
```
E, [2015-09-20T16:52:27.461625 #12191] ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!
E, [2015-09-20T16:52:27.503944 #12194] ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!
E, [2015-09-20T16:52:27.566674 #12197] ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!
E, [2015-09-20T16:52:27.652780 #12188] ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!
```
It throws one of these errors for every fork. These celluloid errors are loud, and are actually adding 10 additional (asynchronous) seconds to site.process build.

**My question:** Is there any way to preemptively terminate celluloid actors from Jekyll Site? If so, I can terminate these actors preemptively from each fork, and prevent these loud errors from celluloid.

Thank you for your help.

**Comment by parkr** [comment]
Do this happen only when serving, or also when building?

**Comment by untra** [comment]
This only happens when serving, after the first build. If I run `jekyll build`, it will work just fine. When serving, the first initial build works fine, but then once the webserver has started, forking Jekyll makes celluloid shout errors.

**Comment by parkr** [comment]
@untra I see. The threading model we use right now could be improved. Have you tried threading and using something like jruby?

**Comment by untra** [comment]
There are two approaches to parallelizing Jekyll's `site.process`: forking it, or threading it. We've been forking (because ruby makes it super easy, and it works!), but it's definitely a clunkier approach, and aside from this issue it works fine. Threading is harder, as there are multiple variables and resources that `site.process` uses that aren't thread safe. Site.process can be easily forked, but it can't be easily threaded.

I ought to setup a public github repo with some experiments demonstrating forking / threading issues.

We haven't tried jruby.

**Comment by parkr** [comment]
Indeed. Perhaps @e2 has some insights here.

**Comment by e2** [comment]
The fix: just upgrade to Listen 3.x (it doesn't use Celluloid).

If there are still problems when using fork(), open an issue in https://github.com/guard/listen.

Details: This is a known problem in Celluloid, but despite asking to backport the patch for it, a fixed version of Celluloid was never released.

**Comment by e2** [comment]
@parkr - I highly recommend Listen 3.x in every situation, unless TCP functionality is needed (not available in Listen 3.x).

**Comment by untra** [comment]
Oh Snap! @e2, you're the guy who made [this contribution to celluloid](https://github.com/celluloid/celluloid/pull/513). This is exactly what I was looking for.

Can confirm, using Listen 3.x ensures celluloid shuts down gracefully when Jekyll is forked. Nice call!
This issue can be closed!

**Comment by parkr** [comment]
Fixed by #25.

**Comment by e2** [comment]
@untra - actually, I believe that Celluloid patch never made it through (long story, mostly a mess) and I'm unsure if it's even handled in the latest version. 

Listen 3.x works because it doesn't use Celluloid at all (Celluloid is never started). If you use any other gem that actually uses Celluloid, you'll likely run into the same problem.

**Comment by untra** [comment]
@e2 That's a shame. It looks like that patch was going to do exactly what was needed. I have a few other projects that use celluloid, but this is the first time I've encountered this.

Thanks again for your help!
