### ISSUE TITLE
update listen gem?

### ISSUE THREAD

**Issue by HenryKobin** [jekyll/jekyll-watch#47]
I noticed in the gemfile it said to update listen when Ruby 2.1 becomes EOL or jekyll 4 comes out. [As of March 31st, 2017](https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/), 2.1 is no longer being patched. Is it time we look into testing Jekyll-Watch with a newer version of Listen?

cc: @jekyllbot @parkr

**Comment by ashmaroli** [comment]
### Note:
**`listen-3.1.5` requires `RUBY_VERSION >= 2.2.3`**
while **`jekyll v3.x`** has a more relaxed requirement: **`RUBY_VERSION >= 2.0.0`**.

---
Ergo, it may involve unexpected issues for users on **`RUBY_VERSION >= 2.2.0 < 2.2.3`**

**Comment by HenryKobin** [comment]
ahh @ashmaroli I feel like such a newb! Got it. Thanks!
