### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by DirtyF** [jekyll/jekyll-watch#54]
Time to cut a new gem after #50 

- [x] Drop Support for Jekyll 2.x

**Comment by mattr-** [comment]
Should this be 1.5.1 or should it be 2.0.0 due since we're not backwards compatible with Ruby 2.0 anymore? ¯\\_(ツ)\_/¯

**Comment by pathawks** [comment]
[Changelog](https://github.com/jekyll/jekyll-watch/compare/v1.5.0...master)

**Comment by pathawks** [comment]
If we do `2.0.0` we should also drop support for Jekyll 2.x

**Comment by mattr-** [comment]
Let’s do it. Get all the cleanups in there. We shouldn’t be afraid of
bumping version numbers. 😃

**Comment by pluehne** [comment]
@DirtyF, @mattr, @pathawks: Thanks for pushing the 2.0 release forward :smiley:. The pull requests #55, #56, and #57 all look good to me! Is there anything left to be done for the 2.0 release that I could help with?

**Comment by DirtyF** [comment]
Fixed by https://github.com/jekyll/jekyll-watch/commit/96f79310a624eb9731e4035d597f384404ee22df
