### ISSUE TITLE
jekyll-watch requires Ruby version >= 2.4.0

### ISSUE THREAD

**Issue by normcyr** [jekyll/jekyll-watch#85]
When following the instructions to install Jekyll on Debian 9.8, I get the following error:

`jekyll-watch requires Ruby version >= 2.4.0.`

Checking the Ruby version:

```bash
$ ruby -v
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
```

Then running 

```bash
$ gem install jekyll-watch
ERROR:  Error installing jekyll-watch:
        The last version of jekyll-watch (>= 0) to support your Ruby & RubyGems was 2.1.2. Try installing it with `gem install jekyll-watch -v 2.1.2`
        jekyll-watch requires Ruby version >= 2.4.0. The current ruby version is 2.3.3.222.
```

Installation instructions for Jekyll should include details with regards to incompatibility with the new version of `jekyll-watch`.

Running `gem install jekyll-watch -v 2.1.2` solves the problem, but this is not appropriate on the long run.

**Comment by ashmaroli** [comment]
The answer lies in the following line:
```
jekyll-watch requires Ruby version >= 2.4.0. The current ruby version is 2.3.3.222.
```
Your Ruby version does not allow installing the latest version.
Upgrading your Ruby version is better for *the long run* especially because Ruby 2.3 will stop receiving security updates from March 31st 2019 onwards.

**Comment by mattr-** [comment]
We should not have bumped the Ruby dependency like this without a major version bump.

@normcyr You can run `gem install -v 2.1.2 jekyll-watch` in order to get a version that's supported by the OS you're using without having to do a bunch of extra work to upgrade Ruby, etc.

**Comment by mattr-** [comment]
@DirtyF Can you yank `2.2.0` from Rubygems and release a `3.0.0` for `jekyll-watch` please?

**Comment by normcyr** [comment]
@mattr- Thanks. This is what I did and everything went fine.
Maybe it is more a pure Jekyll issue though as the installation instructions are not (yet) up to date for Debian.

**Comment by ashmaroli** [comment]
@normcyr We've just released a new version.
Please try installing it by running `gem update jekyll-watch`.

Please close this issue if installation is successful else provide feedback with error messages.
Thank you.

Moreover, you may open a separate ticket to report any unrelated issue(s) with the current release.

**Comment by normcyr** [comment]
Things have worked. Thanks!
